# Generated by Django 5.0.1 on 2024-01-17 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_product_category_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='url',
            field=models.CharField(max_length=1000),
        ),
    ]
