# Generated by Django 5.0.1 on 2024-01-21 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_media_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='url',
            field=models.URLField(max_length=1000),
        ),
    ]
